<?php

global $countries;
$countries = array(
  "AD" => array("en_GB" => "Andorra", "default" => "Andorra"),
  "AE" => array("en_GB" => "United Arab Emirates", "default" => "Spojené arabské emiráty"),
  "AF" => array("en_GB" => "Afghanistan", "default" => "Afganistan"),
  "AG" => array("en_GB" => "Antigua And Barbuda", "default" => "Antigua a Barbuda"),
  "AI" => array("en_GB" => "Anguilla", "default" => "Anguilla"),
  "AL" => array("en_GB" => "Albania", "default" => "Albánsko"),
  "AM" => array("en_GB" => "Armenia", "default" => "Arménsko"),
  "AO" => array("en_GB" => "Angola", "default" => "Angola"),
  "AQ" => array("en_GB" => "Antarctica", "default" => "Antarktída"),
  "AR" => array("en_GB" => "Argentina", "default" => "Argentína"),
  "AS" => array("en_GB" => "American Samoa", "default" => "American Samoa"),
  "AT" => array("en_GB" => "Austria", "default" => "Rakúsko"),
  "AU" => array("en_GB" => "Australia", "default" => "Austrália"),
  "AW" => array("en_GB" => "Aruba", "default" => "Aruba"),
  "AZ" => array("en_GB" => "Azerbaijan", "default" => "Azerbajdžan"),
  "BA" => array("en_GB" => "Bosnia And Herzegowina", "default" => "Bosna a Hercegovina"),
  "BB" => array("en_GB" => "Barbados", "default" => "Barbados"),
  "BD" => array("en_GB" => "Bangladesh", "default" => "Bangladéš"),
  "BE" => array("en_GB" => "Belgium", "default" => "Belgicko"),
  "BF" => array("en_GB" => "Burkina Faso", "default" => "Burkina Faso"),
  "BG" => array("en_GB" => "Bulgaria", "default" => "Bulharsko"),
  "BH" => array("en_GB" => "Bahrain", "default" => "Bahrajn"),
  "BI" => array("en_GB" => "Burundi", "default" => "Burundi"),
  "BJ" => array("en_GB" => "Benin", "default" => "Benin"),
  "BM" => array("en_GB" => "Bermuda", "default" => "Bermuda"),
  "BN" => array("en_GB" => "Brunei Darussalam", "default" => "Brunej"),
  "BO" => array("en_GB" => "Bolivia", "default" => "Bolívia"),
  "BR" => array("en_GB" => "Brazil", "default" => "Brazília"),
  "BS" => array("en_GB" => "Bahamas", "default" => "Bahamy"),
  "BT" => array("en_GB" => "Bhutan", "default" => "Bhután"),
  "BV" => array("en_GB" => "Bouvet Island", "default" => "Bouvet Island"),
  "BW" => array("en_GB" => "Botswana", "default" => "Botswana"),
  "BY" => array("en_GB" => "Belarus", "default" => "Bielorusko"),
  "BZ" => array("en_GB" => "Belize", "default" => "Belize"),
  "CA" => array("en_GB" => "Canada", "default" => "Kanada"),
  "CC" => array("en_GB" => "Cocos (Keeling) Islands", "default" => "Cocos (Keeling) Islands"),
  "CD" => array("en_GB" => "Congo, The Democratic Republic Of The", "default" => "Konžská demokratická republika"),
  "CF" => array("en_GB" => "Central African Republic", "default" => "Stredoafrická republika"),
  "CG" => array("en_GB" => "Congo", "default" => "Kongo"),
  "CH" => array("en_GB" => "Switzerland", "default" => "Švajčiarsko"),
  "CI" => array("en_GB" => "Cote D'Ivoire", "default" => "Cote D'Ivoire"),
  "CK" => array("en_GB" => "Cook Islands", "default" => "Cook Islands"),
  "CL" => array("en_GB" => "Chile", "default" => "Čile"),
  "CM" => array("en_GB" => "Cameroon", "default" => "Kamerun"),
  "CN" => array("en_GB" => "China", "default" => "Čína"),
  "CO" => array("en_GB" => "Colombia", "default" => "Kolumbia"),
  "CR" => array("en_GB" => "Costa Rica", "default" => "Kostarika"),
  "CU" => array("en_GB" => "Cuba", "default" => "Kuba"),
  "CV" => array("en_GB" => "Cape Verde", "default" => "Kapverdy"),
  "CX" => array("en_GB" => "Christmas Island", "default" => "Vianočný ostrov"),
  "CY" => array("en_GB" => "Cyprus", "default" => "Cyprus"),
  "CZ" => array("en_GB" => "Czech Republic", "default" => "Česká republika"),
  "DE" => array("en_GB" => "Germany", "default" => "Nemecko"),
  "DJ" => array("en_GB" => "Djibouti", "default" => "Djibouti"),
  "DK" => array("en_GB" => "Denmark", "default" => "Dánsko"),
  "DM" => array("en_GB" => "Dominica", "default" => "Dominika"),
  "DO" => array("en_GB" => "Dominican Republic", "default" => "Dominikánska republika"),
  "DZ" => array("en_GB" => "Algeria", "default" => "Alžírsko"),
  "EC" => array("en_GB" => "Ecuador", "default" => "Ekvádor"),
  "EE" => array("en_GB" => "Estonia", "default" => "Estónsko"),
  "EG" => array("en_GB" => "Egypt", "default" => "Egypt"),
  "EH" => array("en_GB" => "Western Sahara", "default" => "Západná Sahara"),
  "ER" => array("en_GB" => "Eritrea", "default" => "Eritrea"),
  "ES" => array("en_GB" => "Spain", "default" => "Španielsko"),
  "ET" => array("en_GB" => "Ethiopia", "default" => "Etiópia"),
  "FI" => array("en_GB" => "Finland", "default" => "Fínsko"),
  "FJ" => array("en_GB" => "Fiji", "default" => "Fidži"),
  "FK" => array("en_GB" => "Falkland Islands (Malvinas)", "default" => "Falklandy"),
  "FM" => array("en_GB" => "Micronesia, Federated States Of", "default" => "Mikronézia"),
  "FO" => array("en_GB" => "Faroe Islands", "default" => "Faroe Islands"),
  "FR" => array("en_GB" => "France", "default" => "Francúzsko"),
  "GA" => array("en_GB" => "Gabon", "default" => "Gabon"),
  "GB" => array("en_GB" => "United Kingdom", "default" => "Veľká Británia"),
  "GD" => array("en_GB" => "Grenada", "default" => "Grenada"),
  "GE" => array("en_GB" => "Georgia", "default" => "Gruzínsko"),
  "GH" => array("en_GB" => "Ghana", "default" => "Ghana"),
  "GI" => array("en_GB" => "Gibraltar", "default" => "Gibraltar"),
  "GL" => array("en_GB" => "Greenland", "default" => "Gronsko"),
  "GM" => array("en_GB" => "Gambia", "default" => "Gambia"),
  "GN" => array("en_GB" => "Guinea", "default" => "Guinea"),
  "GP" => array("en_GB" => "Guadeloupe", "default" => "Guadeloupe"),
  "GQ" => array("en_GB" => "Equatorial Guinea", "default" => "Guinea"),
  "GR" => array("en_GB" => "Greece", "default" => "Grécko"),
  "GT" => array("en_GB" => "Guatemala", "default" => "Guatemala"),
  "GU" => array("en_GB" => "Guam", "default" => "Guam"),
  "GW" => array("en_GB" => "Guinea-Bissau", "default" => "Guinea-Bissau"),
  "GY" => array("en_GB" => "Guyana", "default" => "Guayana"),
  "HK" => array("en_GB" => "Hong Kong", "default" => "Hong Kong"),
  "HN" => array("en_GB" => "Honduras", "default" => "Honduras"),
  "HR" => array("en_GB" => "Croatia", "default" => "Chorvátsko"),
  "HT" => array("en_GB" => "Haiti", "default" => "Haiti"),
  "HU" => array("en_GB" => "Hungary", "default" => "Maďarsko"),
  "ID" => array("en_GB" => "Indonesia", "default" => "Indonézia"),
  "IE" => array("en_GB" => "Ireland", "default" => "Írsko"),
  "IL" => array("en_GB" => "Israel", "default" => "Izrael"),
  "IN" => array("en_GB" => "India", "default" => "India"),
  "IO" => array("en_GB" => "British Indian Ocean Territory", "default" => "British Indian Ocean Territory"),
  "IQ" => array("en_GB" => "Iraq", "default" => "Irak"),
  "IR" => array("en_GB" => "Iran", "default" => "Irán"),
  "IS" => array("en_GB" => "Iceland", "default" => "Island"),
  "IT" => array("en_GB" => "Italy", "default" => "Taliansko"),
  "JM" => array("en_GB" => "Jamaica", "default" => "Jamajka"),
  "JO" => array("en_GB" => "Jordan", "default" => " Jordánsko"),
  "JP" => array("en_GB" => "Japan", "default" => "Japonsko"),
  "KE" => array("en_GB" => "Kenya", "default" => "Keňa"),
  "KG" => array("en_GB" => "Kyrgyzstan", "default" => "Kyrgyzstan"),
  "KH" => array("en_GB" => "Cambodia", "default" => "Kambodža"),
  "KI" => array("en_GB" => "Kiribati", "default" => "Kiribati"),
  "KM" => array("en_GB" => "Comoros", "default" => "Komory"),
  "KN" => array("en_GB" => "Saint Kitts And Nevis", "default" => "Svätý Krištof a Nevis"),
  "KP" => array("en_GB" => "Korea, Democratic People's Republic Of", "default" => "Kórejská ľudovodemokratická republika"),
  "KR" => array("en_GB" => "Korea, Republic Of", "default" => "Kórejská republika"),
  "KW" => array("en_GB" => "Kuwait", "default" => "Kuvajt"),
  "KY" => array("en_GB" => "Cayman Islands", "default" => "Cayman Islands"),
  "KZ" => array("en_GB" => "Kazakhstan", "default" => "Kazachstan"),
  "LA" => array("en_GB" => "Lao People's Democratic Republic", "default" => "Laos"),
  "LB" => array("en_GB" => "Lebanon", "default" => "Libanon"),
  "LC" => array("en_GB" => "Saint Lucia", "default" => "Svätá Lucia"),
  "LI" => array("en_GB" => "Liechtenstein", "default" => "Lichtenštajnsko"),
  "LK" => array("en_GB" => "Sri Lanka", "default" => "Sri Lanka"),
  "LR" => array("en_GB" => "Liberia", "default" => "Libéria"),
  "LS" => array("en_GB" => "Lesotho", "default" => "Lesotho"),
  "LT" => array("en_GB" => "Lithuania", "default" => "Litva"),
  "LU" => array("en_GB" => "Luxembourg", "default" => "Luxembursko"),
  "LV" => array("en_GB" => "Latvia", "default" => "Lotyšsko"),
  "LY" => array("en_GB" => "Libyan Arab Jamahiriya", "default" => "Líbya"),
  "MA" => array("en_GB" => "Morocco", "default" => "Maroko"),
  "MC" => array("en_GB" => "Monaco", "default" => "Monako"),
  "MD" => array("en_GB" => "Moldova, Republic Of", "default" => "Moldavsko"),
  "MG" => array("en_GB" => "Madagascar", "default" => "Madagaskar"),
  "MH" => array("en_GB" => "Marshall Islands", "default" => "Marshallove ostrovy"),
  "MK" => array("en_GB" => "Macedonia, Former Yugoslav Republic Of", "default" => "Macedónsko"),
  "ML" => array("en_GB" => "Mali", "default" => "Mali"),
  "MM" => array("en_GB" => "Myanmar", "default" => "Mjanmarsko"),
  "MN" => array("en_GB" => "Mongolia", "default" => "Mongolsko"),
  "MO" => array("en_GB" => "Macau", "default" => "Macao"),
  "MP" => array("en_GB" => "Northern Mariana Islands", "default" => "Northern Mariana Islands"),
  "MQ" => array("en_GB" => "Martinique", "default" => "Martinik"),
  "MR" => array("en_GB" => "Mauritania", "default" => "Mauritánia"),
  "MS" => array("en_GB" => "Montserrat", "default" => "Montserrat"),
  "MT" => array("en_GB" => "Malta", "default" => "Malta"),
  "MU" => array("en_GB" => "Mauritius", "default" => "Maurícius"),
  "MV" => array("en_GB" => "Maldives", "default" => "Maldivy"),
  "MW" => array("en_GB" => "Malawi", "default" => "Malawi"),
  "MX" => array("en_GB" => "Mexico", "default" => "Mexiko"),
  "MY" => array("en_GB" => "Malaysia", "default" => "Malajzia"),
  "MZ" => array("en_GB" => "Mozambique", "default" => "Mozambik"),
  "NA" => array("en_GB" => "Namibia", "default" => "Namíbia"),
  "NC" => array("en_GB" => "New Caledonia", "default" => "Nová Kaledónia"),
  "NE" => array("en_GB" => "Niger", "default" => "Niger"),
  "NF" => array("en_GB" => "Norfolk Island", "default" => "Norfolk Island"),
  "NG" => array("en_GB" => "Nigeria", "default" => "Nigéria"),
  "NI" => array("en_GB" => "Nicaragua", "default" => "Nikaragua"),
  "NL" => array("en_GB" => "Netherlands", "default" => "Holandsko"),
  "NO" => array("en_GB" => "Norway", "default" => "Nórsko"),
  "NP" => array("en_GB" => "Nepal", "default" => "Nepál"),
  "NR" => array("en_GB" => "Nauru", "default" => "Nauru"),
  "NU" => array("en_GB" => "Niue", "default" => "Niue"),
  "NZ" => array("en_GB" => "New Zealand", "default" => "Nový Zéland"),
  "OM" => array("en_GB" => "Oman", "default" => "Omán"),
  "PA" => array("en_GB" => "Panama", "default" => "Panama"),
  "PE" => array("en_GB" => "Peru", "default" => "Peru"),
  "PG" => array("en_GB" => "Papua New Guinea", "default" => "Papua-Nová Guinea"),
  "PH" => array("en_GB" => "Philippines", "default" => "Filipíny"),
  "PK" => array("en_GB" => "Pakistan", "default" => "Pakistan"),
  "PL" => array("en_GB" => "Poland", "default" => "Poľsko"),
  "PN" => array("en_GB" => "Pitcairn", "default" => "Pitcairn"),
  "PR" => array("en_GB" => "Puerto Rico", "default" => "Puerto Rico"),
  "PT" => array("en_GB" => "Portugal", "default" => "Portugalsko"),
  "PW" => array("en_GB" => "Palau", "default" => "Palau"),
  "PY" => array("en_GB" => "Paraguay", "default" => "Paraguaj"),
  "QA" => array("en_GB" => "Qatar", "default" => "Qatar"),
  "RO" => array("en_GB" => "Romania", "default" => "Rumunsko"),
  "RU" => array("en_GB" => "Russian Federation", "default" => "Rusko"),
  "RW" => array("en_GB" => "Rwanda", "default" => "Rwanda"),
  "SA" => array("en_GB" => "Saudi Arabia", "default" => "Saudská Arábia"),
  "SB" => array("en_GB" => "Solomon Islands", "default" => "Šalamúnove ostrovy"),
  "SC" => array("en_GB" => "Seychelles", "default" => "Seychely"),
  "SD" => array("en_GB" => "Sudan", "default" => "Sudán"),
  "SE" => array("en_GB" => "Sweden", "default" => "Švédsko"),
  "SG" => array("en_GB" => "Singapore", "default" => "Singapur"),
  "SH" => array("en_GB" => "St. Helena", "default" => "Svätá Helena"),
  "SI" => array("en_GB" => "Slovenia", "default" => "Slovinsko"),
  "SK" => array("en_GB" => "Slovak Republic", "default" => "Slovenská republika"),
  "SL" => array("en_GB" => "Sierra Leone", "default" => "Sierra Leone"),
  "SM" => array("en_GB" => "San Marino", "default" => "San Maríno"),
  "SN" => array("en_GB" => "Senegal", "default" => "Senegal"),
  "SO" => array("en_GB" => "Somalia", "default" => "Somálsko"),
  "SR" => array("en_GB" => "Suriname", "default" => "Surinam"),
  "ST" => array("en_GB" => "Sao Tome And Principe", "default" => "Sv. Tomáš a Princov Ostrov"),
  "SV" => array("en_GB" => "El Salvador", "default" => "Salvádor"),
  "SY" => array("en_GB" => "Syrian Arab Republic", "default" => "Sýria"),
  "SZ" => array("en_GB" => "Swaziland", "default" => "Svazijsko"),
  "TD" => array("en_GB" => "Chad", "default" => "Čad"),
  "TG" => array("en_GB" => "Togo", "default" => "Togo"),
  "TH" => array("en_GB" => "Thailand", "default" => "Thajsko"),
  "TJ" => array("en_GB" => "Tajikistan", "default" => "Tadžikistan"),
  "TK" => array("en_GB" => "Tokelau", "default" => "Tokelau"),
  "TM" => array("en_GB" => "Turkmenistan", "default" => "Turkménsko"),
  "TN" => array("en_GB" => "Tunisia", "default" => "Tunisko"),
  "TO" => array("en_GB" => "Tonga", "default" => "Tonga"),
  "TP" => array("en_GB" => "East Timor", "default" => "Východný Timor"),
  "TR" => array("en_GB" => "Turkey", "default" => "Turecko"),
  "TT" => array("en_GB" => "Trinidad And Tobago", "default" => "Trinidad a Tobago"),
  "TV" => array("en_GB" => "Tuvalu", "default" => "Tuvalu"),
  "TW" => array("en_GB" => "Taiwan", "default" => "Taiwan"),
  "TZ" => array("en_GB" => "Tanzania, United Republic Of", "default" => "Tanzánia"),
  "UA" => array("en_GB" => "Ukraine", "default" => "Ukrajina"),
  "UG" => array("en_GB" => "Uganda", "default" => "Uganda"),
  "US" => array("en_GB" => "United States", "default" => "Spojené štáty americké"),
  "UY" => array("en_GB" => "Uruguay", "default" => "Uruguaj"),
  "UZ" => array("en_GB" => "Uzbekistan", "default" => "Uzbekistan"),
  "VC" => array("en_GB" => "Saint Vincent And The Grenadines", "default" => "Sv. Vincent a Grenadíny"),
  "VE" => array("en_GB" => "Venezuela", "default" => "Venezuela"),
  "VI" => array("en_GB" => "Virgin Islands", "default" => "Panenské ostrovy"),
  "VN" => array("en_GB" => "Viet Nam", "default" => "Vietnam"),
  "VU" => array("en_GB" => "Vanuatu", "default" => "Vanuatu"),
  "WS" => array("en_GB" => "Samoa", "default" => "Samoa"),
  "YE" => array("en_GB" => "Yemen", "default" => "Jemen"),
  "YT" => array("en_GB" => "Mayotte", "default" => "Mayotte"),
  "YU" => array("en_GB" => "Yugoslavia", "default" => "Juhoslávia"),
  "ZA" => array("en_GB" => "South Africa", "default" => "Južná Afrika"),
  "ZM" => array("en_GB" => "Zambia", "default" => "Zambia"),
  "ZW" => array("en_GB" => "Zimbabwe", "default" => "Zimbabwe")
);

function countries_sorted($lang) {
	$arr = array();

	global $countries;
	foreach ($countries as $key => $value)
		$arr[$key] = $value[$lang];

	if ($lang == 'default')
		$lang = 'sk_SK';
	$old = setlocale(LC_COLLATE, "$lang.utf8");
	uasort($arr, 'strcoll');
	setlocale(LC_COLLATE, $old);

	return $arr;
}

?>
